# Generated by Django 5.2.11 on 2026-02-10 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('example_1', models.CharField(blank=True, default='', max_length=200)),
                ('example_2', models.CharField(blank=True, default='', max_length=200)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='core.rule')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sentence', models.TextField()),
                ('sentence_type', models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong')], max_length=10)),
                ('source', models.CharField(choices=[('book', 'Book'), ('ai', 'AI'), ('manual', 'Manual')], default='book', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review_1_done', 'Review 1 Done'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='core.rule')),
            ],
            options={
                'ordering': ['sentence_id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('review_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.sentence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='core.source'),
        ),
    ]
